In [2]:
import pandas as pd
import numpy as np

In [4]:
x=[1, 2, 3]
y=[4, 5, 6]
z=[7, 8, 9]

print(np.concatenate([x, y, z]))
print(np.vstack([x, y, z]))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
ser1=pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2=pd.Series(['D', 'E', 'F'], index=[4,5,6])

print(ser1, '\n\n', ser2)


1    A
2    B
3    C
dtype: object 

 4    D
5    E
6    F
dtype: object


In [8]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data, ind)

print(make_df('ABC', [1,2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [9]:
df1= make_df('AB', [1,2])
df2= make_df('AB', [3,4])

print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [11]:
df3= make_df('AB', [0,1])
df4= make_df('CD', [0,1])

print(df3, '\n\n', df4)
print(pd.concat([df3, df4]))

    A   B
0  A0  B0
1  A1  B1 

     C   D
0  C0  D0
1  C1  D1
     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1


In [12]:
df3=pd.merge(df1, df2)
print(df3)

Empty DataFrame
Columns: [A, B]
Index: []
