In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [4]:
lst = [1, 2, 3, 4]
arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
print(arr.dtype)
a = np.array([1.1, 1.2, 2.5])
print(a.dtype)

int32
float64


In [12]:
from sys import getsizeof

lst=[]
print(getsizeof(lst))

lst1=[1,2]
print(getsizeof(lst1))

arr = np.array([])
print(getsizeof(arr))

56
72
104


In [20]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 +2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

student_scores=np.array([test_1, test_2, test_3_fixed])
print(student_scores)
print(student_scores.shape)

jeremy_test_2 = student_scores[1,3]
print(jeremy_test_2)

manul_adwoa_test_1 = np.array([student_scores[0,1], student_scores[0,2]])
print(manul_adwoa_test_1)

print(student_scores[:,4])

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
(3, 5)
93
[94 88]
[87 91 94]


In [27]:
a= np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a>5
print(mask)

selected = a[a>5]
print(selected)

selected = a[(a>5) | (a<4)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
