In [3]:
import numpy as np

In [4]:
print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [8]:
arr1 = np.random.randint(10, size = 6)
print(arr1)

arr2 = np.random.randint(10, size = (3,4,5))
print(arr2)

[6 0 1 0 2 7]
[[[1 5 4 8 2]
  [7 2 3 0 7]
  [5 8 4 9 9]
  [3 1 6 2 3]]

 [[1 6 7 5 3]
  [2 6 4 5 7]
  [0 6 7 8 6]
  [1 7 4 2 2]]

 [[5 1 4 6 5]
  [6 5 4 0 9]
  [6 2 9 6 5]
  [0 4 3 7 5]]]


In [10]:
np.random.seed(1)
arr=np.random.randint(10, size = (3,4))
print(arr)
print("arr.ndim = ",arr.ndim)
print("arr.shape = ",arr.shape)
print("arr.size = ",arr.size)
print("arr.itemsize = ",arr.itemsize)
print("arr.nbytes = ",arr.nbytes)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
arr.ndim =  2
arr.shape =  (3, 4)
arr.size =  12
arr.itemsize =  4
arr.nbytes =  48


In [13]:
arr = np.arange(10)
print(arr)
print(arr[3:7])
print(arr[:9:3])
print(arr[1:9:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 3 6]
[1 3 5 7]


In [14]:
np.random.seed(2)
arr=np.random.randint(10, size = (6,8))
print(arr)

arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0,0] = 99
print(arr)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8  6  2  8  7  2  1]
 [ 5  4  4  5  7  3  6  4]
 [ 3  7  6  1  3  5  8  4]
 [ 6  3  9  2  0  4  2  4]
 [ 1  7  8  2  9  8  7  1]
 [ 6  8  5  9  9  9  3  0]]


In [16]:
np.random.seed(3)
arr= np.random.randint(10, size =(6,8))
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub)


[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]
[[8 9]
 [9 9]]


In [17]:
arr_new = arr[:, np.newaxis]
print(arr_new)
arint(arr_new.shape, '/n')

[[[8 9 3 8 8 0 5 3]]

 [[9 9 5 7 6 0 4 7]]

 [[8 1 6 2 2 1 3 5]]

 [[8 1 8 7 8 1 0 5]]

 [[4 1 5 4 7 6 0 0]]

 [[9 2 4 5 8 8 7 5]]]


NameError: name 'arint' is not defined

In [21]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array([7,8,9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
