In [3]:
import numpy as np
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/ values[i]
    return output

values=np.random.randint(1,10,size=5)
print(values)

compute_reciprocals(values)


[4 8 7 1 7]


array([0.25      , 0.125     , 0.14285714, 1.        , 0.14285714])

In [4]:
big_array=np.random.randint(1,100, size=1000000)

%timeit compute_reciprocals(big_array)



2.22 s ± 129 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit 1/ big_array


3.37 ms ± 154 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
np.random.seed(1)
arr1= np.random.randint(10, size=(5))
arr2= np.random.randint(10, size=(5))
print(arr1, arr2)

arr1 =arr1 -2
print(arr1)

arr3=arr1+arr2
print(arr3)

arr4=np.random.randint(10, size=(3,5))
print(arr4)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]


In [11]:
x=np.arange(4)
print("x     =",x)
print("x + 5 =",x+5)
print("x - 5 =",x-5)
print("x * 2 =",x*2)
print("x / 2 =",x/2)
print("x ** 2 =",x**2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [12]:
x=np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x=np.array([3-4j, 2+0j, 3+6j])
print(np.abs(x))

[2 1 0 1 2]
[5.         2.         6.70820393]


In [15]:
theta=np.linspace(0,np.pi, 3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [16]:
x=np.arange(1,5)
print(x)

aggr= np.add.reduce(x)
print(aggr)

aggr=np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [18]:
x=np.arange(1,15)
print(x)

accum=np.multiply.accumulate(x)
print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [21]:
np.random.seed(2)
arr=np.random.rand(10000000)

print(arr)
print('sum=',np.sum(arr))

%timeit sum(arr)

[0.4359949  0.02592623 0.54966248 ... 0.92851865 0.66632148 0.12215498]
sum= 5000127.333888764
835 ms ± 46.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
np.random.seed(5)
arr=np.random.randint(10, size = (3,4))
print(arr)

print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[15 28  8]
