In [1]:
import numpy as np

In [2]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
a=np.arange(3)
print(a)
a=a[:,np.newaxis]
print(a)

[0 1 2]
[[0]
 [1]
 [2]]


In [4]:
b=np.arange(3)
print(b)

print(a+b)

[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [5]:
a=np.ones((3,2))
print(a)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
x=np.array([1,2,3,4,5])
print(x<3)
print(x>=3)
print(x!=3)
print(x==3)

[ True  True False False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [11]:
np.random.seed(0)
a= np.random.randint(10, size=(3,4))
print(a)

print(a<6)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In [13]:
print(a)
print(np.count_nonzero(a<6))

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
8


In [14]:
print(a)
print(a<5)
print(a[a<5])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]


In [16]:
np.random.seed(1)
x=np.random.randint(100, size=10)
a=x[2]; b=x[4];c=x[6]

In [18]:
np.random.seed(2)
x=np.random.randint(10,size=(3,5))
print(x)

row=[0,1,2]
col=[2,1,4]

print(x[row,col])

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]
[6 2 6]


In [21]:
print(x)

row=np.array([0,1,2])
col=np.array([2,1,4])
x[row[:,np.newaxis],col]

[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]]


array([[6, 8, 8],
       [1, 2, 4],
       [7, 5, 6]])

In [23]:
x=np.arange(1,13).reshape(3,4)
print(x)

ind=
print(x[2,ind])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


NameError: name 'ind' is not defined